#!/bin/bash
echo -e "\e[32mInstalling depends..."
apt install gnupg curl -y > /dev/null 2>&1 

echo adding sources demo-tools repo 
sleep 2
if [[ ! -d $PREFIX/etc/apt/sources.list.d ]]; then
  mkdir -p $PREFIX/etc/apt/sources.list.d > /dev/null 2>&1
fi  
echo "deb [trusted=yes arch=all] https://raw.githubusercontent.com/Nano7795/kumbra/main stable main" > $PREFIX/etc/apt/sources.list.d/demo.list

echo -e "\e[32mAdding keys for demo-tools repo\e[0m"
curl -sL https://raw.githubusercontent.com/Nano7795/kumbra/main/hh.key | apt-key add
sleep 2

mv $PREFIX/etc/apt/trusted.gpg $PREFIX/etc/apt/trusted.gpg.d > /dev/null 2>&1

printf "\n 
Demo-tools Repo installed....
updating repositories...
"
apt update -y
